# Generated by Django 4.2.7 on 2024-12-01 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Burger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('deskripsi', models.TextField()),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pelanggan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pelanggan', models.CharField(max_length=255)),
                ('pesanan', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pemesanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_pemesanan', models.DateTimeField(auto_now_add=True)),
                ('total_harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status_pembayaran', models.BooleanField(default=False)),
                ('burger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.burger')),
                ('pelanggan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pelanggan')),
            ],
        ),
        migrations.CreateModel(
            name='DetailPemesanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.PositiveIntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('burger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.burger')),
                ('pemesanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pemesanan')),
            ],
        ),
    ]
