# Generated by Django 4.2.7 on 2024-12-01 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_burger_pelanggan_pemesanan_detailpemesanan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelanggan',
            name='pesanan',
        ),
        migrations.AddField(
            model_name='pelanggan',
            name='pesanan',
            field=models.ManyToManyField(related_name='pelanggans', to='main.burger'),
        ),
    ]
