# Generated by Django 4.2.7 on 2024-12-01 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_pelanggan_pesanan_pelanggan_pesanan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pemesanan',
            name='tanggal_pemesanan',
        ),
    ]
