# Generated by Django 4.2.7 on 2024-12-01 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_pemesanan_tanggal_pemesanan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pemesanan',
            name='total_harga',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
