# Generated by Django 4.2.7 on 2024-12-01 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_pemesanan_burger_pemesanan_burger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailpemesanan',
            name='jumlah',
        ),
        migrations.RemoveField(
            model_name='detailpemesanan',
            name='subtotal',
        ),
    ]
