# Generated by Django 4.2.7 on 2024-12-02 00:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_detailpemesanan_jumlah_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pemesanan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
