# Generated by Django 4.2.7 on 2024-12-01 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pelanggan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pemesanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_pemesanan', models.DateTimeField(auto_now_add=True)),
                ('total_harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status_pembayaran', models.BooleanField(default=False)),
                ('pelanggan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.pelanggan')),
            ],
        ),
        migrations.CreateModel(
            name='DetailPemesanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.PositiveIntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('burger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.burger')),
                ('pemesanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.pemesanan')),
            ],
        ),
    ]
